import { useState } from 'react';

const data = [
  {
    id: 1,
    key: 1,
    flightNo: 'BS 7',
    leg: {
      start: 'PJM',
      end: 'HRZ',
    },
    depTime: '10:59',
    arrTime: '18:12',
    assignedAircraft: '',
    permissibleAircrafts: ['ATR72, B738, DH8D'],
  },
  {
    id: 2,
    key: 2,
    flightNo: 'BS 15',
    leg: {
      start: 'DOY',
      end: 'EOK',
    },
    depTime: '18:03',
    arrTime: '3:57',
    assignedAircraft: 'DH8D',
    permissibleAircrafts: ['ATR72'],
  },
  {
    id: 3,
    key: 3,
    flightNo: 'BS 2193',
    leg: {
      start: 'YLL',
      end: 'SKO',
    },
    depTime: '6:06',
    arrTime: '5:19',
    assignedAircraft: '',
    permissibleAircrafts: ['DH8D, ATR72, B738'],
  },
  {
    id: 4,
    key: 4,
    flightNo: 'BS 25',
    leg: {
      start: 'KCD',
      end: 'EVH',
    },
    depTime: '7:45',
    arrTime: '6:39',
    assignedAircraft: 'DH8D',
    permissibleAircrafts: ['ATR72'],
  },
  {
    id: 5,
    key: 5,
    flightNo: 'BS 5610',
    leg: {
      start: 'TNZ',
      end: 'LTG',
    },
    depTime: '17:15',
    arrTime: '8:48',
    assignedAircraft: '',
    permissibleAircrafts: ['DH8D'],
  },
  {
    id: 6,
    key: 6,
    flightNo: 'BS 757',
    leg: {
      start: 'MNQ',
      end: 'NOA',
    },
    depTime: '22:49',
    arrTime: '0:56',
    assignedAircraft: 'B738',
    permissibleAircrafts: ['ATR72, B738'],
  },
  {
    id: 7,
    key: 7,
    flightNo: 'BS 152',
    leg: {
      start: 'GNV',
      end: 'KAS',
    },
    depTime: '17:04',
    arrTime: '9:33',
    assignedAircraft: 'ATR72',
    permissibleAircrafts: ['ATR72'],
  },
  {
    id: 8,
    key: 8,
    flightNo: 'BS 993',
    leg: {
      start: 'HBD',
      end: 'PPB',
    },
    depTime: '16:11',
    arrTime: '16:12',
    assignedAircraft: '',
    permissibleAircrafts: ['B738'],
  },
  {
    id: 9,
    key: 9,
    flightNo: 'BS 55',
    leg: {
      start: 'PNR',
      end: 'SCD',
    },
    depTime: '18:08',
    arrTime: '8:06',
    assignedAircraft: '',
    permissibleAircrafts: ['DH8D'],
  },
  {
    id: 10,
    key: 10,
    flightNo: 'BS 49',
    leg: {
      start: 'OTI',
      end: 'YFA',
    },
    depTime: '18:50',
    arrTime: '19:47',
    assignedAircraft: '',
    permissibleAircrafts: ['DH8D'],
  },
  {
    id: 11,
    key: 11,
    flightNo: 'BS 2054',
    leg: {
      start: 'RRS',
      end: 'IFN',
    },
    depTime: '17:35',
    arrTime: '1:32',
    assignedAircraft: '',
    permissibleAircrafts: ['ATR72'],
  },
  {
    id: 12,
    key: 12,
    flightNo: 'BS 1462',
    leg: {
      start: 'CKW',
      end: 'GKN',
    },
    depTime: '15:46',
    arrTime: '1:01',
    assignedAircraft: '',
    permissibleAircrafts: ['DH8D, B738, ATR72'],
  },
  {
    id: 13,
    key: 13,
    flightNo: 'BS 664',
    leg: {
      start: 'AOJ',
      end: 'TUZ',
    },
    depTime: '7:20',
    arrTime: '14:43',
    assignedAircraft: 'DH8D',
    permissibleAircrafts: ['DH8D, B738, ATR72'],
  },
  {
    id: 14,
    key: 14,
    flightNo: 'BS 782',
    leg: {
      start: 'FNT',
      end: 'GHA',
    },
    depTime: '0:52',
    arrTime: '22:22',
    assignedAircraft: '',
    permissibleAircrafts: ['B738'],
  },
  {
    id: 15,
    key: 15,
    flightNo: 'BS 13',
    leg: {
      start: 'VTG',
      end: 'MDF',
    },
    depTime: '11:32',
    arrTime: '14:02',
    assignedAircraft: '',
    permissibleAircrafts: ['ATR72, B738'],
  },
  {
    id: 16,
    key: 16,
    flightNo: 'BS 280',
    leg: {
      start: 'HSC',
      end: 'YDF',
    },
    depTime: '3:48',
    arrTime: '5:24',
    assignedAircraft: 'B738',
    permissibleAircrafts: ['ATR72, DH8D'],
  },
  {
    id: 17,
    key: 17,
    flightNo: 'BS 656',
    leg: {
      start: 'BEV',
      end: 'ULC',
    },
    depTime: '14:08',
    arrTime: '2:42',
    assignedAircraft: 'DH8D',
    permissibleAircrafts: ['DH8D, B738'],
  },
  {
    id: 18,
    key: 18,
    flightNo: 'BS 16',
    leg: {
      start: 'SUA',
      end: 'NQU',
    },
    depTime: '18:46',
    arrTime: '8:06',
    assignedAircraft: '',
    permissibleAircrafts: ['ATR72'],
  },
  {
    id: 19,
    key: 19,
    flightNo: 'BS 800',
    leg: {
      start: 'XIG',
      end: 'FLE',
    },
    depTime: '21:20',
    arrTime: '12:22',
    assignedAircraft: 'ATR72',
    permissibleAircrafts: ['ATR72, DH8D'],
  },
  {
    id: 20,
    key: 20,
    flightNo: 'BS 72',
    leg: {
      start: 'RYN',
      end: 'ATT',
    },
    depTime: '21:48',
    arrTime: '15:11',
    assignedAircraft: '',
    permissibleAircrafts: ['ATR72, B738'],
  },
  {
    id: 21,
    key: 21,
    flightNo: 'BS 12',
    leg: {
      start: 'CXB',
      end: 'CCO',
    },
    depTime: '6:31',
    arrTime: '0:10',
    assignedAircraft: '',
    permissibleAircrafts: ['ATR72, DH8D'],
  },
  {
    id: 22,
    key: 22,
    flightNo: 'BS 1001',
    leg: {
      start: 'JXN',
      end: 'LPL',
    },
    depTime: '20:57',
    arrTime: '7:38',
    assignedAircraft: '',
    permissibleAircrafts: ['B738'],
  },
  {
    id: 23,
    key: 23,
    flightNo: 'BS 576',
    leg: {
      start: 'BXM',
      end: 'AAB',
    },
    depTime: '8:52',
    arrTime: '0:29',
    assignedAircraft: '',
    permissibleAircrafts: ['ATR72'],
  },
  {
    id: 24,
    key: 24,
    flightNo: 'BS 398',
    leg: {
      start: 'DGP',
      end: 'ETR',
    },
    depTime: '9:10',
    arrTime: '22:47',
    assignedAircraft: '',
    permissibleAircrafts: ['DH8D'],
  },
  {
    id: 25,
    key: 25,
    flightNo: 'BS 75',
    leg: {
      start: 'TOH',
      end: 'RKW',
    },
    depTime: '18:18',
    arrTime: '1:47',
    assignedAircraft: 'B738',
    permissibleAircrafts: ['B738'],
  },
  {
    id: 26,
    key: 26,
    flightNo: 'BS 60',
    leg: {
      start: 'RCO',
      end: 'KFA',
    },
    depTime: '18:09',
    arrTime: '4:16',
    assignedAircraft: '',
    permissibleAircrafts: ['ATR72, DH8D, B738'],
  },
  {
    id: 27,
    key: 27,
    flightNo: 'BS 60',
    leg: {
      start: 'SEK',
      end: 'BDL',
    },
    depTime: '22:23',
    arrTime: '19:34',
    assignedAircraft: 'DH8D',
    permissibleAircrafts: ['DH8D, ATR72'],
  },
  {
    id: 28,
    key: 28,
    flightNo: 'BS 3670',
    leg: {
      start: 'KMZ',
      end: 'HHE',
    },
    depTime: '19:36',
    arrTime: '8:03',
    assignedAircraft: 'ATR72',
    permissibleAircrafts: ['ATR72'],
  },
  {
    id: 29,
    key: 29,
    flightNo: 'BS 699',
    leg: {
      start: 'DUA',
      end: 'QDJ',
    },
    depTime: '1:50',
    arrTime: '2:22',
    assignedAircraft: 'B738',
    permissibleAircrafts: ['DH8D, ATR72'],
  },
  {
    id: 30,
    key: 30,
    flightNo: 'BS 6500',
    leg: {
      start: 'KGH',
      end: 'RVO',
    },
    depTime: '18:37',
    arrTime: '12:09',
    assignedAircraft: '',
    permissibleAircrafts: ['B738, DH8D, ATR72'],
  },
  {
    id: 31,
    key: 31,
    flightNo: 'BS 6527',
    leg: {
      start: 'LII',
      end: 'CVB',
    },
    depTime: '12:08',
    arrTime: '1:46',
    assignedAircraft: 'B738',
    permissibleAircrafts: ['B738'],
  },
  {
    id: 32,
    key: 32,
    flightNo: 'BS 6548',
    leg: {
      start: 'EGE',
      end: 'QSX',
    },
    depTime: '14:30',
    arrTime: '9:10',
    assignedAircraft: '',
    permissibleAircrafts: ['B738, ATR72, DH8D'],
  },
  {
    id: 33,
    key: 33,
    flightNo: 'BS 89',
    leg: {
      start: 'DAV',
      end: 'OTS',
    },
    depTime: '1:41',
    arrTime: '6:10',
    assignedAircraft: '',
    permissibleAircrafts: ['ATR72, B738, DH8D'],
  },
  {
    id: 34,
    key: 34,
    flightNo: 'BS 362',
    leg: {
      start: 'RKY',
      end: 'CRR',
    },
    depTime: '13:00',
    arrTime: '21:45',
    assignedAircraft: '',
    permissibleAircrafts: ['ATR72, B738, DH8D'],
  },
  {
    id: 35,
    key: 35,
    flightNo: 'BS 170',
    leg: {
      start: 'SKB',
      end: 'YAK',
    },
    depTime: '23:48',
    arrTime: '1:54',
    assignedAircraft: '',
    permissibleAircrafts: ['DH8D, ATR72, B738'],
  },
  {
    id: 36,
    key: 36,
    flightNo: 'BS 551',
    leg: {
      start: 'SQE',
      end: 'CAE',
    },
    depTime: '1:34',
    arrTime: '20:26',
    assignedAircraft: '',
    permissibleAircrafts: ['ATR72, DH8D'],
  },
  {
    id: 37,
    key: 37,
    flightNo: 'BS 174',
    leg: {
      start: 'RYG',
      end: 'ROS',
    },
    depTime: '18:27',
    arrTime: '5:16',
    assignedAircraft: 'B738',
    permissibleAircrafts: ['B738, ATR72, DH8D'],
  },
  {
    id: 38,
    key: 38,
    flightNo: 'BS 1245',
    leg: {
      start: 'QVR',
      end: 'YAY',
    },
    depTime: '3:47',
    arrTime: '23:06',
    assignedAircraft: '',
    permissibleAircrafts: ['B738, ATR72, DH8D'],
  },
  {
    id: 39,
    key: 39,
    flightNo: 'BS 653',
    leg: {
      start: 'CDJ',
      end: 'GOI',
    },
    depTime: '12:03',
    arrTime: '4:37',
    assignedAircraft: 'ATR72',
    permissibleAircrafts: ['ATR72'],
  },
  {
    id: 40,
    key: 40,
    flightNo: 'BS 427',
    leg: {
      start: 'PMN',
      end: 'LHR',
    },
    depTime: '18:38',
    arrTime: '4:47',
    assignedAircraft: 'B738',
    permissibleAircrafts: ['DH8D, ATR72'],
  },
  {
    id: 41,
    key: 41,
    flightNo: 'BS 1801',
    leg: {
      start: 'KLI',
      end: 'CLH',
    },
    depTime: '7:09',
    arrTime: '22:38',
    assignedAircraft: '',
    permissibleAircrafts: ['DH8D'],
  },
  {
    id: 42,
    key: 42,
    flightNo: 'BS 7284',
    leg: {
      start: 'LAR',
      end: 'OOR',
    },
    depTime: '10:46',
    arrTime: '16:49',
    assignedAircraft: 'ATR72',
    permissibleAircrafts: ['DH8D, ATR72, B738'],
  },
  {
    id: 43,
    key: 43,
    flightNo: 'BS 16',
    leg: {
      start: 'YTY',
      end: 'ISI',
    },
    depTime: '22:13',
    arrTime: '1:31',
    assignedAircraft: '',
    permissibleAircrafts: ['B738, ATR72, DH8D'],
  },
  {
    id: 44,
    key: 44,
    flightNo: 'BS 15',
    leg: {
      start: 'POP',
      end: 'FME',
    },
    depTime: '19:47',
    arrTime: '23:24',
    assignedAircraft: '',
    permissibleAircrafts: ['ATR72, B738'],
  },
  {
    id: 45,
    key: 45,
    flightNo: 'BS 259',
    leg: {
      start: 'GOP',
      end: 'BPX',
    },
    depTime: '12:34',
    arrTime: '7:01',
    assignedAircraft: 'ATR72',
    permissibleAircrafts: ['DH8D'],
  },
  {
    id: 46,
    key: 46,
    flightNo: 'BS 40',
    leg: {
      start: 'PNH',
      end: 'BWU',
    },
    depTime: '7:41',
    arrTime: '16:02',
    assignedAircraft: 'B738',
    permissibleAircrafts: ['B738'],
  },
  {
    id: 47,
    key: 47,
    flightNo: 'BS 3048',
    leg: {
      start: 'YQL',
      end: 'WWR',
    },
    depTime: '21:34',
    arrTime: '8:29',
    assignedAircraft: '',
    permissibleAircrafts: ['ATR72'],
  },
  {
    id: 48,
    key: 48,
    flightNo: 'BS 1033',
    leg: {
      start: 'BXK',
      end: 'VCH',
    },
    depTime: '22:26',
    arrTime: '21:00',
    assignedAircraft: '',
    permissibleAircrafts: ['B738, ATR72, DH8D'],
  },
  {
    id: 49,
    key: 49,
    flightNo: 'BS 1067',
    leg: {
      start: 'AKC',
      end: 'GMD',
    },
    depTime: '9:24',
    arrTime: '10:38',
    assignedAircraft: '',
    permissibleAircrafts: ['B738'],
  },
  {
    id: 50,
    key: 50,
    flightNo: 'BS 13',
    leg: {
      start: 'SZX',
      end: 'EMM',
    },
    depTime: '6:42',
    arrTime: '15:27',
    assignedAircraft: 'ATR72',
    permissibleAircrafts: ['ATR72, DH8D'],
  },
  {
    id: 51,
    key: 51,
    flightNo: 'BS 58',
    leg: {
      start: 'WON',
      end: 'CLY',
    },
    depTime: '17:35',
    arrTime: '9:06',
    assignedAircraft: 'DH8D',
    permissibleAircrafts: ['B738'],
  },
  {
    id: 52,
    key: 52,
    flightNo: 'BS 1',
    leg: {
      start: 'RKO',
      end: 'KHD',
    },
    depTime: '9:34',
    arrTime: '6:01',
    assignedAircraft: 'B738',
    permissibleAircrafts: ['DH8D, ATR72'],
  },
  {
    id: 53,
    key: 53,
    flightNo: 'BS 298',
    leg: {
      start: 'PIB',
      end: 'CAP',
    },
    depTime: '5:15',
    arrTime: '14:51',
    assignedAircraft: 'ATR72',
    permissibleAircrafts: ['ATR72, B738, DH8D'],
  },
  {
    id: 54,
    key: 54,
    flightNo: 'BS 1474',
    leg: {
      start: 'RAH',
      end: 'BFH',
    },
    depTime: '16:46',
    arrTime: '15:59',
    assignedAircraft: 'ATR72',
    permissibleAircrafts: ['DH8D'],
  },
  {
    id: 55,
    key: 55,
    flightNo: 'BS 958',
    leg: {
      start: 'BHQ',
      end: 'MXR',
    },
    depTime: '14:34',
    arrTime: '15:52',
    assignedAircraft: '',
    permissibleAircrafts: ['DH8D'],
  },
  {
    id: 56,
    key: 56,
    flightNo: 'BS 14219',
    leg: {
      start: 'BPX',
      end: 'WVB',
    },
    depTime: '4:04',
    arrTime: '0:48',
    assignedAircraft: 'DH8D',
    permissibleAircrafts: ['DH8D'],
  },
  {
    id: 57,
    key: 57,
    flightNo: 'BS 81',
    leg: {
      start: 'WST',
      end: 'CSN',
    },
    depTime: '5:33',
    arrTime: '23:21',
    assignedAircraft: 'ATR72',
    permissibleAircrafts: ['ATR72'],
  },
  {
    id: 58,
    key: 58,
    flightNo: 'BS 670',
    leg: {
      start: 'RMD',
      end: 'PTW',
    },
    depTime: '9:10',
    arrTime: '13:59',
    assignedAircraft: 'ATR72',
    permissibleAircrafts: ['B738, DH8D, ATR72'],
  },
  {
    id: 59,
    key: 59,
    flightNo: 'BS 3800',
    leg: {
      start: 'SHY',
      end: 'MWT',
    },
    depTime: '15:08',
    arrTime: '8:51',
    assignedAircraft: 'ATR72',
    permissibleAircrafts: ['ATR72, B738'],
  },
  {
    id: 60,
    key: 60,
    flightNo: 'BS 20',
    leg: {
      start: 'HED',
      end: 'MWO',
    },
    depTime: '13:11',
    arrTime: '19:53',
    assignedAircraft: 'ATR72',
    permissibleAircrafts: ['DH8D'],
  },
  {
    id: 61,
    key: 61,
    flightNo: 'BS 53',
    leg: {
      start: 'OBL',
      end: 'KWB',
    },
    depTime: '5:28',
    arrTime: '20:28',
    assignedAircraft: 'ATR72',
    permissibleAircrafts: ['B738, DH8D'],
  },
  {
    id: 62,
    key: 62,
    flightNo: 'BS 253',
    leg: {
      start: 'TJV',
      end: 'MCG',
    },
    depTime: '0:01',
    arrTime: '3:50',
    assignedAircraft: 'ATR72',
    permissibleAircrafts: ['ATR72, DH8D'],
  },
  {
    id: 63,
    key: 63,
    flightNo: 'BS 3757',
    leg: {
      start: '0',
      end: 'JCH',
    },
    depTime: '7:58',
    arrTime: '4:08',
    assignedAircraft: '',
    permissibleAircrafts: ['ATR72'],
  },
  {
    id: 64,
    key: 64,
    flightNo: 'BS 1198',
    leg: {
      start: 'OUM',
      end: 'UPL',
    },
    depTime: '7:03',
    arrTime: '21:37',
    assignedAircraft: 'DH8D',
    permissibleAircrafts: ['B738'],
  },
  {
    id: 65,
    key: 65,
    flightNo: 'BS 160',
    leg: {
      start: 'RMN',
      end: 'KMQ',
    },
    depTime: '19:44',
    arrTime: '11:25',
    assignedAircraft: '',
    permissibleAircrafts: ['DH8D, B738'],
  },
  {
    id: 66,
    key: 66,
    flightNo: 'BS 142',
    leg: {
      start: 'ITA',
      end: 'LKA',
    },
    depTime: '19:14',
    arrTime: '0:46',
    assignedAircraft: '',
    permissibleAircrafts: ['DH8D'],
  },
  {
    id: 67,
    key: 67,
    flightNo: 'BS 12816',
    leg: {
      start: 'YUS',
      end: 'POO',
    },
    depTime: '15:02',
    arrTime: '17:49',
    assignedAircraft: 'B738',
    permissibleAircrafts: ['DH8D'],
  },
  {
    id: 68,
    key: 68,
    flightNo: 'BS 2170',
    leg: {
      start: 'ZAR',
      end: 'XPR',
    },
    depTime: '13:51',
    arrTime: '9:16',
    assignedAircraft: '',
    permissibleAircrafts: ['DH8D'],
  },
  {
    id: 69,
    key: 69,
    flightNo: 'BS 79',
    leg: {
      start: 'AAP',
      end: 'KAF',
    },
    depTime: '12:02',
    arrTime: '8:16',
    assignedAircraft: 'B738',
    permissibleAircrafts: ['B738, DH8D, ATR72'],
  },
  {
    id: 70,
    key: 70,
    flightNo: 'BS 40',
    leg: {
      start: 'GOE',
      end: 'TRU',
    },
    depTime: '10:52',
    arrTime: '3:21',
    assignedAircraft: '',
    permissibleAircrafts: ['B738'],
  },
  {
    id: 71,
    key: 71,
    flightNo: 'BS 823',
    leg: {
      start: 'DJO',
      end: 'AOP',
    },
    depTime: '1:59',
    arrTime: '11:40',
    assignedAircraft: 'DH8D',
    permissibleAircrafts: ['DH8D, ATR72, B738'],
  },
  {
    id: 72,
    key: 72,
    flightNo: 'BS 623',
    leg: {
      start: 'ACB',
      end: 'AER',
    },
    depTime: '20:18',
    arrTime: '2:43',
    assignedAircraft: 'B738',
    permissibleAircrafts: ['B738, DH8D'],
  },
  {
    id: 73,
    key: 73,
    flightNo: 'BS 2312',
    leg: {
      start: 'EDW',
      end: 'DVR',
    },
    depTime: '9:50',
    arrTime: '2:40',
    assignedAircraft: 'ATR72',
    permissibleAircrafts: ['DH8D, B738'],
  },
  {
    id: 74,
    key: 74,
    flightNo: 'BS 226',
    leg: {
      start: 'FZO',
      end: 'VAM',
    },
    depTime: '16:39',
    arrTime: '13:53',
    assignedAircraft: '',
    permissibleAircrafts: ['ATR72'],
  },
  {
    id: 75,
    key: 75,
    flightNo: 'BS 39',
    leg: {
      start: 'LBV',
      end: 'WPO',
    },
    depTime: '4:33',
    arrTime: '3:43',
    assignedAircraft: '',
    permissibleAircrafts: ['B738, DH8D'],
  },
  {
    id: 76,
    key: 76,
    flightNo: 'BS 3500',
    leg: {
      start: 'RPX',
      end: 'GUI',
    },
    depTime: '9:19',
    arrTime: '2:53',
    assignedAircraft: 'ATR72',
    permissibleAircrafts: ['ATR72, DH8D'],
  },
  {
    id: 77,
    key: 77,
    flightNo: 'BS 1242',
    leg: {
      start: 'YVC',
      end: 'AOO',
    },
    depTime: '9:39',
    arrTime: '22:39',
    assignedAircraft: '',
    permissibleAircrafts: ['B738, DH8D'],
  },
  {
    id: 78,
    key: 78,
    flightNo: 'BS 30',
    leg: {
      start: 'XYE',
      end: 'CYG',
    },
    depTime: '8:19',
    arrTime: '22:08',
    assignedAircraft: 'DH8D',
    permissibleAircrafts: ['DH8D, ATR72, B738'],
  },
  {
    id: 79,
    key: 79,
    flightNo: 'BS 963',
    leg: {
      start: 'TGM',
      end: 'URC',
    },
    depTime: '10:49',
    arrTime: '22:13',
    assignedAircraft: '',
    permissibleAircrafts: ['B738, DH8D, ATR72'],
  },
  {
    id: 80,
    key: 80,
    flightNo: 'BS 249',
    leg: {
      start: 'YOT',
      end: 'DLI',
    },
    depTime: '6:50',
    arrTime: '16:56',
    assignedAircraft: 'B738',
    permissibleAircrafts: ['DH8D, B738, ATR72'],
  },
  {
    id: 81,
    key: 81,
    flightNo: 'BS 930',
    leg: {
      start: 'BSS',
      end: 'JIK',
    },
    depTime: '22:02',
    arrTime: '21:03',
    assignedAircraft: 'B738',
    permissibleAircrafts: ['B738, ATR72, DH8D'],
  },
  {
    id: 82,
    key: 82,
    flightNo: 'BS 14',
    leg: {
      start: 'LNA',
      end: 'PBZ',
    },
    depTime: '20:12',
    arrTime: '2:24',
    assignedAircraft: '',
    permissibleAircrafts: ['B738, ATR72'],
  },
  {
    id: 83,
    key: 83,
    flightNo: 'BS 40',
    leg: {
      start: 'RMI',
      end: 'EIH',
    },
    depTime: '6:55',
    arrTime: '0:00',
    assignedAircraft: '',
    permissibleAircrafts: ['DH8D'],
  },
  {
    id: 84,
    key: 84,
    flightNo: 'BS 70',
    leg: {
      start: 'MUF',
      end: 'SBX',
    },
    depTime: '5:23',
    arrTime: '5:06',
    assignedAircraft: 'B738',
    permissibleAircrafts: ['ATR72'],
  },
  {
    id: 85,
    key: 85,
    flightNo: 'BS 116',
    leg: {
      start: 'ISC',
      end: 'LMO',
    },
    depTime: '1:22',
    arrTime: '1:46',
    assignedAircraft: 'DH8D',
    permissibleAircrafts: ['DH8D, B738, ATR72'],
  },
  {
    id: 86,
    key: 86,
    flightNo: 'BS 12',
    leg: {
      start: 'FAF',
      end: 'SKQ',
    },
    depTime: '11:27',
    arrTime: '18:47',
    assignedAircraft: 'DH8D',
    permissibleAircrafts: ['DH8D'],
  },
  {
    id: 87,
    key: 87,
    flightNo: 'BS 75',
    leg: {
      start: 'DPK',
      end: 'SXT',
    },
    depTime: '2:53',
    arrTime: '20:32',
    assignedAircraft: 'DH8D',
    permissibleAircrafts: ['B738, DH8D, ATR72'],
  },
  {
    id: 88,
    key: 88,
    flightNo: 'BS 3245',
    leg: {
      start: 'TID',
      end: 'WBM',
    },
    depTime: '4:09',
    arrTime: '16:18',
    assignedAircraft: 'ATR72',
    permissibleAircrafts: ['DH8D, B738'],
  },
  {
    id: 89,
    key: 89,
    flightNo: 'BS 402',
    leg: {
      start: 'OLV',
      end: 'FAS',
    },
    depTime: '4:59',
    arrTime: '1:31',
    assignedAircraft: 'B738',
    permissibleAircrafts: ['DH8D, B738, ATR72'],
  },
  {
    id: 90,
    key: 90,
    flightNo: 'BS 357',
    leg: {
      start: 'MAB',
      end: 'IKL',
    },
    depTime: '14:25',
    arrTime: '16:34',
    assignedAircraft: '',
    permissibleAircrafts: ['ATR72'],
  },
  {
    id: 91,
    key: 91,
    flightNo: 'BS 325',
    leg: {
      start: 'EUA',
      end: 'MWQ',
    },
    depTime: '2:28',
    arrTime: '23:46',
    assignedAircraft: '',
    permissibleAircrafts: ['ATR72, DH8D, B738'],
  },
  {
    id: 92,
    key: 92,
    flightNo: 'BS 1490',
    leg: {
      start: 'ELR',
      end: 'TZR',
    },
    depTime: '17:47',
    arrTime: '13:20',
    assignedAircraft: 'DH8D',
    permissibleAircrafts: ['DH8D, B738, ATR72'],
  },
  {
    id: 93,
    key: 93,
    flightNo: 'BS 131',
    leg: {
      start: 'EMS',
      end: 'TNH',
    },
    depTime: '7:38',
    arrTime: '23:18',
    assignedAircraft: 'DH8D',
    permissibleAircrafts: ['B738, ATR72, DH8D'],
  },
  {
    id: 94,
    key: 94,
    flightNo: 'BS 53',
    leg: {
      start: 'OBL',
      end: 'HFS',
    },
    depTime: '4:53',
    arrTime: '13:27',
    assignedAircraft: '',
    permissibleAircrafts: ['DH8D'],
  },
  {
    id: 95,
    key: 95,
    flightNo: 'BS 105',
    leg: {
      start: 'MVD',
      end: 'FLP',
    },
    depTime: '11:54',
    arrTime: '6:08',
    assignedAircraft: '',
    permissibleAircrafts: ['B738, ATR72'],
  },
  {
    id: 96,
    key: 96,
    flightNo: 'BS 10',
    leg: {
      start: 'KPC',
      end: 'HPA',
    },
    depTime: '15:20',
    arrTime: '0:02',
    assignedAircraft: '',
    permissibleAircrafts: ['DH8D, ATR72, B738'],
  },
  {
    id: 97,
    key: 97,
    flightNo: 'BS 262',
    leg: {
      start: 'JBR',
      end: 'AEP',
    },
    depTime: '4:51',
    arrTime: '2:03',
    assignedAircraft: 'ATR72',
    permissibleAircrafts: ['B738, DH8D'],
  },
  {
    id: 98,
    key: 98,
    flightNo: 'BS 12',
    leg: {
      start: 'NQU',
      end: 'XPP',
    },
    depTime: '0:20',
    arrTime: '8:14',
    assignedAircraft: '',
    permissibleAircrafts: ['ATR72'],
  },
  {
    id: 99,
    key: 99,
    flightNo: 'BS 4100',
    leg: {
      start: 'GCT',
      end: 'BPF',
    },
    depTime: '14:29',
    arrTime: '13:20',
    assignedAircraft: 'B738',
    permissibleAircrafts: ['DH8D'],
  },
  {
    id: 100,
    key: 100,
    flightNo: 'BS 6800',
    leg: {
      start: 'WAB',
      end: 'GGW',
    },
    depTime: '18:58',
    arrTime: '16:08',
    assignedAircraft: '',
    permissibleAircrafts: ['B738'],
  },
];
const columns = [
  {
    title: 'Flight No.',
    dataIndex: 'flightNo',
    render: (text) => <span>{text}</span>,
  },
  {
    title: 'Leg',
    dataIndex: 'leg',
    render: (text) => <span>{text?.start + ' - ' + text?.end}</span>,
  },
  {
    title: 'Dep. Time',
    dataIndex: 'depTime',
  },
  {
    title: 'Arr. Time',
    dataIndex: 'arrTime',
  },
  {
    title: 'Permissble Aircraft',
    dataIndex: 'permissibleAircrafts',
  },
  {
    title: 'Assigned Aircraft',
    dataIndex: 'assignedAircraft',
  },
];
const useAssignAircraft = () => {
  const [selectedRows, setSelectedRows] = useState([]);

  // handle selected rows on change
  const handleRowsOnChange = (selectedRowKeys, _selectedRows) => {
    setSelectedRows(_selectedRows);
  };
  return {
    data,
    columns,
    handleRowsOnChange,
    selectedRows,
  };
};

export default useAssignAircraft;
